name: 'owari-action'
description: xztaityozx/owariを使って終わりをお知らせするactionです
inputs:
  args:
    description: owariコマンドへの引数です
    default: 'default'
  as-summary:
    description: owariコマンドの出力をstepのSummaryとして出力します
    default: false
outputs:
  content:
    description: owariコマンドの出力結果です
runs:
  using: docker
  image: Dockerfile
  env:
    OWARI_AS_STEP_SUMMARY: ${{inputs.as-summary}}
    OWARI_ENABLE_OUTPUT: true
  args:
    - ${{ inputs.args }}
