# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker build -t xztaityozx/owari-action ./

  test:
    deps: [build]
    cmds:
      - if [[ "$(docker run --rm xztaityozx/owari-action | sha256sum)" == "23bc7618122252f4e2f5ea6f42993c6bcb2868b7422037f9df944c6a876d3793  -" ]] then echo ok; fi

