# https://taskfile.dev

version: '3'

env:
  SHA_DEFAULT_OUTPUT: ./assets/sha-default

tasks:
  default:
    cmds:
      - docker run --rm xztaityozx/owari-action {{.CLI_ARGS}}

  build:
    cmds:
      - docker build -t xztaityozx/owari-action ./

  rebuild:
    cmds:
      - docker build --no-cache -t xztaityozx/owari-action ./

  test:
    deps: [build]
    cmds:
      - if ! echo {{.CLI_ARGS}} | sha256sum -c {{.SHA_DEFAULT_OUTPUT}}; then exit 1; fi

  act:
    preconditions:
      - type act
    cmds:
      - act --rebuild

