# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - docker run --rm xztaityozx/owari-action false {{.CLI_ARGS}}

  build:
    cmds:
      - docker build -t xztaityozx/owari-action ./

  rebuild:
    cmds:
      - docker build --no-cache -t xztaityozx/owari-action ./

  test:
    deps: [build]
    cmds:
      - if [[ "$(echo {{.CLI_ARGS}} | sha256sum)" != "23bc7618122252f4e2f5ea6f42993c6bcb2868b7422037f9df944c6a876d3793  -" ]] then exit 1; fi

