name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1

      - uses: ./
        id: owari

      - name: Checking output
        run: |
          task test -- "$(echo -e '${{steps.owari.outputs.content}}')"

  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: default
        uses: ./

      - name: owari kanban
        uses: ./
        with:
          args: 'kanban -a xztaityozx owari-action'

      - name: as job summary
        uses: ./
        with:
          as-summary: true

      - uses: ./
        with:
          args: 'kanban -a xztaityozx "これは スペースが 含まれている 文字列"'

  owari:
    needs: [example, build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          as-summary: true
          args: 'kanban -ga \"GitHub Actions\"  "${{github.sha}}のテストは${{ job.status }}だったよ"'
